#:kivy 1.8.0

<NeuronCell>:

<NeuralDisplay>:
	
<DigitalDisplayNode>:
	canvas:
		Color:
			rgb: 1,1,1 
		Rectangle:
			pos: self.pos
			size: self.size

<DigitalDisplay>:
	node1: node_topleft
	node2: node_top
	
	canvas:
		Rectangle:
			pos: 0, 0
			size: 300, 300

	DigitalDisplayNode:
		id: node_topleft
		x: (root.width / 3) - self.width
		y: root.height / 2
		size: 10, root.height / 4

	DigitalDisplayNode:
		id: node_top
		x: root.width / 3
		y: root.height / 4
		size: root.width / 3, 10